apiVersion: v1
kind: Service
metadata:
  name: nginx-sidecar-service
  namespace: default
  labels:
    app: nginx-with-sidecar
spec:
  selector:
    app: nginx-with-sidecar
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx-with-sidecar
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-with-sidecar
  template:
    metadata:
      labels:
        app: nginx-with-sidecar
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      volumes:
        - name: shared
          emptyDir: {}
      initContainers:
        # Main application container
        - name: lw-sidecar
          # Simple sidecar: display log files using nginx.
          # In reality, this sidecar would be a custom image
          # that uploads logs to a third-party or storage service.
          image: 950194951070.dkr.ecr.us-west-2.amazonaws.com/galen-lw-sidecar
          # ports:
          #   - containerPort: 80

          # Mount the pod's shared log file into the sidecar
          # container. In this case, nginx will serve the files
          # in this directory.
          volumeMounts:
          - name: shared
            mountPath: /shared # nginx-specific mount path
      containers:
            - name: app-container
          # Simple application: write the current date
          # to the log file every five seconds
          image: nginx # alpine is a simple Linux OS image
          command: ["/bin/sh""]
          # args: ["-c","/shared/lacework.sh"]

          # Mount the pod's shared log file into the app 
          # container. The app writes logs here.
          volumeMounts:
          - name: shared
            mountPath: /shared
        # Sidecar container
